### ISSUE TITLE
After publishing post, "Syndicate To" doesn't work

### ISSUE THREAD

**Issue by asuh** [dshanske/syndication-links#106]
I write a new post and publish it. I realize I did not check any of the syndication checkboxes in the widget. So I check the box to use Bridgy to send to Twitter. After updating the post, I wait a while and see no new Tweets.

I've only tried this with Twitter so far and it doesn't work.

**Comment by dougbeal** [comment]
Happens to me too!

**Comment by dshanske** [comment]
@asuh  @dougbeal Investigating a few theories. Do either of you use caching?

**Comment by asuh** [comment]
I currently do not use a caching plugin or have anything set up to cache.

**Comment by dougbeal** [comment]
I don’t have caching set up.  The problem was I had restructured my docker networks, and cut external communication for php-fpm .

**Comment by dougbeal** [comment]
Now it is working great.

**Comment by asuh** [comment]
Verified this issue still exists for me. Published latest note without Brid.gy syndication to Twitter, updated post with checkbox ticked to syndicate, no action taken.

**Comment by dshanske** [comment]
That's WP Cron for you.

**Comment by glueckpress** [comment]
@asuh Did you encounter the same problem again?

On my site, the behaviour of the syndication option seems curious: 

- I check the _Twitter via Bridgy_ checkbox.
- I publish the post.
- Next after the screen has reloaded, the checkbox appears unchecked again.
- Nothing gets syndicated.

I think I can exclude WP Cron from the range of possible causes (even though I am using a caching plugin) because there’s quite a lot of activity in wp-admin on my site. 

Appreciate any ideas on what to test, totally out of my wits at the moment.

**Comment by dshanske** [comment]
The box always appears unchecked...that is designed behavior.

**Comment by dshanske** [comment]
Was this post originally a draft?

**Comment by dshanske** [comment]
Compare.to #109

**Comment by glueckpress** [comment]
> The box always appears unchecked...that is designed behavior.

Oh, thanks, this helps! I’m in a rabbit hole with Cloudflare, will report back when I know more.

**Comment by asuh** [comment]
This is a good reminder, I had forgotten to follow up. I tried this again, having saved the post as a draft before publishing and syndicating to Twitter. It took about 2 minutes but I saw my syndicated tweet pointing back to my original post.

I think my original issue is solved (or was just a case of a slow cron job) so I'm going to close this out.
