### ISSUE TITLE
POSSE to Pinboard

### ISSUE THREAD

**Issue by dshanske** [dshanske/syndication-links#136]
POSSE to Pinboard.in and allow for content to be added as notes, and tags to be added as tags to Pinboard itself.

**Comment by willtm** [comment]
**What might be useful from my perspective:**  The Pinboard.in API provides [documentation for the possible `add` arguments](https://pinboard.in/api/#posts_add) (ie, adding a bookmark to Pinboard).  I would be interested in having all of them available with the possible exception of `toread`.  And since this collection of arguments includes the possibility to `replace` a bookmark with an identical URL, it might also be convenient to have a [`delete` option](https://pinboard.in/api/#posts_delete).

**Why it would be useful to me:**  The POSSE workflow (WP->Pinboard.in) is appealing to me since it might allow for more thoughtful link descriptions and comments but would still permit me to use the nice features in Pinboard such as the archive and search both a cached copy of the source URL and my notes and tags.  And as I write this, the ability to save a cached copy of the source URL in Pinboard might be the single greatest feature for me besides the speed and simplicity of Pinboard.

**Comment by dshanske** [comment]
Feature that allows you to posse to Pinboard is built. For now, requires the Post Kinds plugin to figure out what URL to share, but otherwise it works and shows a Syndication Links to the Pinboard version of the URL, also sends any post tags, and the name and description from Post Kinds. Since it doesn't only show up on bookmarks, it can be used for any bookmark.
