### ISSUE TITLE
upgrade to 4.4.2 led to a fatal error

### ISSUE THREAD

**Issue by joejenett** [dshanske/syndication-links#170]
After updating to 4.4.2, I received emails from each of my 2 wordpress installations regarding a fatal error. Following is a copy of the error details and the actions I took to get everything back in order, including upgrading the plugin again.

---copy---
Error Details
=============
An error of type E_COMPILE_ERROR was caused in line 7 of the file /home/joejen5/public_html/dwtp/wp-content/plugins/syndication-links/includes/trait-bridgy-config.php. Error message: Cannot declare trait Bridgy_Config, because the name is already in use
---end copy---

I first restored the plugin to the previous version (from a backup) which enabled my logging in to wp-admin again. Then I deactivated and deleted the Bridgy plugin, and then upgraded Syndication Links to 4.4.2 and everything is working normally again.

Previous upgrades of your plugin never led to any problems.

Hope this helps...

Thanks

**Comment by dshanske** [comment]
Well, there's your answer. You still had the Bridgy plugin installed. It was removed and retired from the repo at least 3 years ago(don't remember the exact date). I moved the syndication code into this plugin. The only other thing it had was a direct registration link to sign up, which I may add here.

Since the other plugin isn't used anymore, I don't think I have a fix for this one.

**Comment by joejenett** [comment]
I wasn’t expecting a fix. Just thought the info would be helpful to you. I’m good. thanks
