### ISSUE TITLE
Syndication Links MetaBox

### ISSUE THREAD

**Issue by dshanske** [dshanske/syndication-links#62]
Explain Syndication Links Metabox better.

**Comment by dshanske** [comment]
Disable the box from displaying by default...

There is a filter, default_hidden_meta_boxes(https://developer.wordpress.org/reference/hooks/default_hidden_meta_boxes/)

**Comment by chrisaldrich** [comment]
<a href="https://github.com/dshanske/syndication-links/issues/62" class="u-in-reply-to"></a>I like the idea of explaining them better and may take a crack at doing so from a documentation standpoint.

If I recall the reason that prompted hiding it by default correctly, I'd be more worried that you're cutting out  a much larger group of users who might not otherwise find the meta box if it were hidden by default than you'd be helping by hiding it.

**Comment by dshanske** [comment]
I am thinking of offering an dynamically expandable metabox. Hit Add to add another URL.

**Comment by dshanske** [comment]
This is resolved.
